[book]
title = "DaniFluffyCat ^^"
authors = ["Daniele - @DaniFluffyCat"]
description = "Artes, projetos pessoais, minicódigos, e o que mais eu criar está aqui :)"
language = "pt"
multilingual = false
src = "src"

[build]
create-missing = false 

[output.html]
cname = "danifluffy.dev"
no-section-label = true
fold.enable = true
default-theme = "navy"
preferred-dark-theme = "navy"